server:
  port: 9000

spring:
  application:
      name: eureka-client
  datasource:
    url: jdbc:mysql://118.24.5.244:3306/wh_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
